camera_1:
  nickname: 'alpha'
  serial_no: '032622070733'
  pose:
    position:
      x: 0.5  # Position in meters (x-axis)
      y: -1.0  # Position in meters (y-axis)
      z: 0.75  # Position in meters (z-axis)
    orientation:
      roll: -1.5  # Rotation around x-axis in radians
      pitch: 0.0  # Rotation around y-axis in radians
      yaw: 0.0  # Rotation around z-axis in radians
