agents:
  panda:
    pose:
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
configurations:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    - finger_joint1
    - finger_joint2